name: "dropwizard-ci-pipeline"

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        working-directory: .
        run: ./gradlew build -x test

      - name: Test
        working-directory: .
        run: ./gradlew test

  system-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Run docker compose
        working-directory: .
        run: docker compose up -d --build

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.19"

      - name: Install python dependencies
        run: pip install pytest requests

      - name: Run system tests
        working-directory: .
        run: pytest

      - name: Bring server down
        if: always()
        working-directory: .
        run: docker compose down
